version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/cityvoice/code
permissions:
   - object: /var/www/cityvoice
     owner: cityvoice
     group: cityvoice
     type:
       - file
   - object: /var/www/cityvoice
     owner: cityvoice
     group: cityvoice
     type:
       - directory
hooks:
   AfterInstall: 
    - location: script/deployupdate.sh
      runas: cityvoice
   ApplicationStart:
    - location: script/nginxrestart.sh
      runas: ubuntu